yes_no_options = ["Yes","No"]
bucket_list = ["rposam-etl-source-datasets-s3"]
pipelines_options = ["Airflow with Snowflake","Airflow with POSTGRES","SNOWPIPE"]
stage_name_options =["MIRROR_DB.MIRROR.STAGE_EXTERNAL_S3"]
encoding_options = ["UTF-8","ASCII", "ISO-8859-1",  "Windows-1252"]
