 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "SILVER";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."SILVER"."T_STG_ORDER_ITEMS" (
    "ORDER_ITEM_ID" TEXT,
    "ORDER_ID" TEXT,
    "PRODUCT_ID" TEXT,
    "USER_ID" TEXT,
    "QUANTITY" NUMERIC,
    "ITEM_PRICE" DOUBLE PRECISION,
    "ITEM_TOTAL" DOUBLE PRECISION,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT,
    "UPDATED_DTS" TIMESTAMP,
    "UPDATED_BY" TEXT,
    "UNIQUE_HASH_ID" TEXT,
    "ROW_HASH_ID" TEXT,
    "ACTIVE_FL" TEXT,
    "EFFECTIVE_START_DATE" TIMESTAMP,
    "EFFECTIVE_END_DATE" TIMESTAMP
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "BRONZE";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."BRONZE"."T_ML_ORDER_ITEMS" (
    "ORDER_ITEM_ID" TEXT,
    "ORDER_ID" TEXT,
    "PRODUCT_ID" TEXT,
    "USER_ID" TEXT,
    "QUANTITY" TEXT,
    "ITEM_PRICE" TEXT,
    "ITEM_TOTAL" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "BRONZE";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."BRONZE"."T_ML_ORDER_ITEMS_TR" (
    "ORDER_ITEM_ID" TEXT,
    "ORDER_ID" TEXT,
    "PRODUCT_ID" TEXT,
    "USER_ID" TEXT,
    "QUANTITY" TEXT,
    "ITEM_PRICE" TEXT,
    "ITEM_TOTAL" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "SILVER";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."SILVER"."T_STG_ORDERS" (
    "ORDER_ID" TEXT,
    "USER_ID" TEXT,
    "ORDER_DATE" TEXT,
    "ORDER_STATUS" TEXT,
    "TOTAL_AMOUNT" DOUBLE PRECISION,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT,
    "UPDATED_DTS" TIMESTAMP,
    "UPDATED_BY" TEXT,
    "UNIQUE_HASH_ID" TEXT,
    "ROW_HASH_ID" TEXT,
    "ACTIVE_FL" TEXT,
    "EFFECTIVE_START_DATE" TIMESTAMP,
    "EFFECTIVE_END_DATE" TIMESTAMP
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "BRONZE";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."BRONZE"."T_ML_ORDERS" (
    "ORDER_ID" TEXT,
    "USER_ID" TEXT,
    "ORDER_DATE" TEXT,
    "ORDER_STATUS" TEXT,
    "TOTAL_AMOUNT" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "BRONZE";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."BRONZE"."T_ML_ORDERS_TR" (
    "ORDER_ID" TEXT,
    "USER_ID" TEXT,
    "ORDER_DATE" TEXT,
    "ORDER_STATUS" TEXT,
    "TOTAL_AMOUNT" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "BRONZE";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."BRONZE"."T_ML_EVENTS" (
    "EVENT_ID" TEXT,
    "USER_ID" TEXT,
    "PRODUCT_ID" TEXT,
    "EVENT_TYPE" TEXT,
    "EVENT_TIMESTAMP" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "BRONZE";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."BRONZE"."T_ML_EVENTS_TR" (
    "EVENT_ID" TEXT,
    "USER_ID" TEXT,
    "PRODUCT_ID" TEXT,
    "EVENT_TYPE" TEXT,
    "EVENT_TIMESTAMP" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "SILVER";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."SILVER"."T_STG_EVENTS" (
    "EVENT_ID" TEXT,
    "USER_ID" TEXT,
    "PRODUCT_ID" TEXT,
    "EVENT_TYPE" TEXT,
    "EVENT_TIMESTAMP" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT,
    "UPDATED_DTS" TIMESTAMP,
    "UPDATED_BY" TEXT,
    "UNIQUE_HASH_ID" TEXT,
    "ROW_HASH_ID" TEXT,
    "ACTIVE_FL" TEXT,
    "EFFECTIVE_START_DATE" TIMESTAMP,
    "EFFECTIVE_END_DATE" TIMESTAMP
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "SILVER";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."SILVER"."T_STG_PRODUCTS" (
    "PRODUCT_ID" TEXT,
    "PRODUCT_NAME" TEXT,
    "CATEGORY" TEXT,
    "BRAND" TEXT,
    "PRICE" DOUBLE PRECISION,
    "RATING" DOUBLE PRECISION,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT,
    "UPDATED_DTS" TIMESTAMP,
    "UPDATED_BY" TEXT,
    "UNIQUE_HASH_ID" TEXT,
    "ROW_HASH_ID" TEXT,
    "ACTIVE_FL" TEXT,
    "EFFECTIVE_START_DATE" TIMESTAMP,
    "EFFECTIVE_END_DATE" TIMESTAMP
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "BRONZE";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."BRONZE"."T_ML_PRODUCTS_TR" (
    "PRODUCT_ID" TEXT,
    "PRODUCT_NAME" TEXT,
    "CATEGORY" TEXT,
    "BRAND" TEXT,
    "PRICE" TEXT,
    "RATING" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "BRONZE";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."BRONZE"."T_ML_PRODUCTS" (
    "PRODUCT_ID" TEXT,
    "PRODUCT_NAME" TEXT,
    "CATEGORY" TEXT,
    "BRAND" TEXT,
    "PRICE" TEXT,
    "RATING" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "SILVER";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."SILVER"."T_STG_REVIEWS" (
    "REVIEW_ID" TEXT,
    "ORDER_ID" TEXT,
    "PRODUCT_ID" TEXT,
    "USER_ID" TEXT,
    "RATING" NUMERIC,
    "REVIEW_TEXT" TEXT,
    "REVIEW_DATE" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT,
    "UPDATED_DTS" TIMESTAMP,
    "UPDATED_BY" TEXT,
    "UNIQUE_HASH_ID" TEXT,
    "ROW_HASH_ID" TEXT,
    "ACTIVE_FL" TEXT,
    "EFFECTIVE_START_DATE" TIMESTAMP,
    "EFFECTIVE_END_DATE" TIMESTAMP
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "BRONZE";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."BRONZE"."T_ML_REVIEWS" (
    "REVIEW_ID" TEXT,
    "ORDER_ID" TEXT,
    "PRODUCT_ID" TEXT,
    "USER_ID" TEXT,
    "RATING" TEXT,
    "REVIEW_TEXT" TEXT,
    "REVIEW_DATE" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "BRONZE";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."BRONZE"."T_ML_REVIEWS_TR" (
    "REVIEW_ID" TEXT,
    "ORDER_ID" TEXT,
    "PRODUCT_ID" TEXT,
    "USER_ID" TEXT,
    "RATING" TEXT,
    "REVIEW_TEXT" TEXT,
    "REVIEW_DATE" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "SILVER";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."SILVER"."T_STG_USERS" (
    "USER_ID" TEXT,
    "NAME" TEXT,
    "EMAIL" TEXT,
    "GENDER" TEXT,
    "CITY" TEXT,
    "SIGNUP_DATE" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT,
    "UPDATED_DTS" TIMESTAMP,
    "UPDATED_BY" TEXT,
    "UNIQUE_HASH_ID" TEXT,
    "ROW_HASH_ID" TEXT,
    "ACTIVE_FL" TEXT,
    "EFFECTIVE_START_DATE" TIMESTAMP,
    "EFFECTIVE_END_DATE" TIMESTAMP
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "BRONZE";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."BRONZE"."T_ML_USERS" (
    "USER_ID" TEXT,
    "NAME" TEXT,
    "EMAIL" TEXT,
    "GENDER" TEXT,
    "CITY" TEXT,
    "SIGNUP_DATE" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);

 CREATE DATABASE IF NOT EXISTS "ECOMMERCE_DB";
 USE DATABASE "ECOMMERCE_DB";
 CREATE SCHEMA IF NOT EXISTS "BRONZE";
  CREATE TABLE IF NOT EXISTS "ECOMMERCE_DB"."BRONZE"."T_ML_USERS_TR" (
    "USER_ID" TEXT,
    "NAME" TEXT,
    "EMAIL" TEXT,
    "GENDER" TEXT,
    "CITY" TEXT,
    "SIGNUP_DATE" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);